name: Build Konary Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 强制拉取，解决 git 权限问题
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y build-essential libssl-dev libelf-dev bc bison flex python2

      - name: Set up environment
        run: |
          echo "PATH=$GITHUB_WORKSPACE/toolchain/clang-r547379/bin:$PATH" >> $GITHUB_ENV

      - name: Run build script
        run: |
          chmod +x buildKonary.sh
          ./buildKonary.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Konary-Kernel-Build
          path: build-official-out/arch/arm64/boot/
